---
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/www/html:delegated
    ports:
      - 8000:8000
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t public


  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: userapi
      POSTGRES_PASSWORD: userapi
      LANG: en_US.utf8
    volumes:
      - db_pg_userapi:/var/lib/postgresql/data:delegated
    ports:
      - 15432:5432

volumes:
  db_pg_userapi: